# Copyright 2022 NEC Corporation
# Released under the MIT license.
# https://opensource.org/licenses/mit-license.php
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: application000001-service
  name: application000001-service
  namespace: <namespace>
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: application000001-api
  type: ClusterIP
