apiVersion: v1
kind: ConfigMap
metadata:
  name: root-region-term-of-use-notification-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "catalogService": {
        "getCatalogName": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2Fname",
        "getForNs": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2F%3Fns%3D"
      },
      "notificationService": {
        "register": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fnotification"
      },
      "bookManageService": {
        "getRegionTargetFind": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fterm_of_use%2Fregion%2Ftarget%2Ffind",
        "getRegionTarget": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fterm_of_use%2Fregion%2Ftarget%3Foffset%3D{offset}%26limit%3D10",
        "getRegionNotificationComplete": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fterm_of_use%2Fregion%2Fnotification%2Fcomplete"
      },
      "session": {
        "loginId": "root_batch",
        "auth": {
          "member": {
            "add": true,
            "update": true
          },
          "book": {
            "create": true
          }
        },
        "block": {
          "_value": 1000401,
          "_ver": 1
        },
        "actor": {
          "_value": 1000431,
          "_ver": 1
        }
      },
      "catalog": {
        "globalSettingNs": "catalog/ext/{extName}/setting/global",
        "pxrRootBlockNs": "catalog/ext/{extName}/block/pxr-root"
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/root/region-term-of-use-notification-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }