apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: root-output-user-data-file-mng-batch
  namespace: pxross1
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 00
  failedJobsHistoryLimit: 2
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: output-user-data-file-mng-batch
            image: ＜ECRのDNS名＞/pxross1:output-user-data-file-mng-batch-container
            imagePullPolicy: IfNotPresent
            command: ["node", "/usr/src/app/createOutputUserDataFileMng.js"]
            volumeMounts:
            - mountPath: /usr/src/app/config
              readOnly: true
              name: output-user-data-file-mng-batch-config
          restartPolicy: OnFailure
          volumes:
          - name: output-user-data-file-mng-batch-config
            configMap:
              name: root-output-user-data-file-mng-batch-container-config-map
