AWSTemplateFormatVersion: 2010-09-09
#Description: 
# --------------------------------------------------
# Parameters Section
# --------------------------------------------------
Parameters:
  ### Required Option
  PrefixName:
    Type: String
    Description: Please input stack prefix name
    AllowedPattern: ^[a-z|0-9|/-]+$
    # ドメインとして使用できない文字は不可
  #TargetURL:
  #  Description: Target URL to monitor
  #  Type: String
  #BlockShortName:
  #  Type: String
  #  AllowedValues:
  #    - 'rt'
  #    - 'rg'
  #    - 'wf'
  #    - 'ap'
  #    - 'tr'
  #    - 'cs'
  #BlockId:
  #  Type: String 
  #  Description: "exmaple: root-api, application000001-api"
  #  Default: root-api
Resources:

  EksLogErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties: 
      FilterPattern: "ERROR"
      LogGroupName: !Sub /aws/eks/${PrefixName}-cluster/cluster
      MetricTransformations: 
        -
          MetricValue: "1"
          DefaultValue: "0"
          #MetricNamespace: !Sub ${PrefixName}-eks
          MetricNamespace: !Sub ${PrefixName}
          MetricName: "eks-log-error"
          
  EksLogError:
    Type: AWS::CloudWatch::Alarm
    Properties:
        AlarmName: !Sub ${PrefixName}-eks-log-error
        ActionsEnabled: true
        OKActions: []
        AlarmActions:
            - !Sub arn:aws:sns:ap-northeast-1:${AWS::AccountId}:${PrefixName}-Alarm-Notification
        InsufficientDataActions: []
        MetricName: !Ref EksLogErrorMetricFilter
        Namespace: !Sub ${PrefixName}
        Statistic: Sum
        Dimensions: []
        Period: 300
        EvaluationPeriods: 1
        DatapointsToAlarm: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching

  CrontabDeadMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties: 
      FilterPattern: 'FailedNeedsStart'
      LogGroupName: !Sub /aws/eks/${PrefixName}-cluster/cluster
      MetricTransformations: 
        -
          MetricValue: "1"
          DefaultValue: "0"
          MetricNamespace: !Sub ${PrefixName}
          MetricName: "podStartFailed"

  CrontabDeadAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
        AlarmName: !Sub ${PrefixName}-podStartFailed
        ActionsEnabled: true
        OKActions: []
        AlarmActions:
            - !Sub arn:aws:sns:ap-northeast-1:${AWS::AccountId}:${PrefixName}-Alarm-Notification
        InsufficientDataActions: []
        MetricName: "podStartFailed"
        Namespace: !Sub ${PrefixName}
        Statistic: Average
        Dimensions: []
        Period: 300
        EvaluationPeriods: 1
        DatapointsToAlarm: 1
        Threshold: 1.0
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching