# Copyright 2022 NEC Corporation
# Released under the MIT license.
# https://opensource.org/licenses/mit-license.php
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config-map
  namespace: <namespace>
data:
  common-conf.json: |
    { 
      "ext_name": "<ext_name>",
      "password": {
        "initLength": 12,
        "hashSalt": "<password_hashsalt>",
        "hashStrechCount": <password_hashStrechCount>
      },
      "cloud_search": {
       "post_url": "https://{endpoint}/{authcode}/documents/batch",
       "get_url": "https://{endpoint}/{authcode}/search",
       "endpoint": "<cloudsearch-endpoint>",
       "authcode": "2013-01-01",
       "size": 100,
       "isUpdate": true
      }
    }

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: application000001-common-config-map
  namespace: <namespace>
data:
  block-common-conf.json: |
    {
      "block": {
        "_value": 1000407,
        "_ver": 1
      },
      "actor": {
        "_value": null,
        "_ver": null
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: root-common-config-map
  namespace: <namespace>
data:
  block-common-conf.json: |
    {
      "block": {
        "_value": 1000401,
        "_ver": 1
      },
      "actor": {
        "_value": null,
        "_ver": null
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: region000001-common-config-map
  namespace: <namespace>
data:
  block-common-conf.json: |
    {
      "block": {
        "_value": 1000402,
        "_ver": 1
      },
      "actor": {
        "_value": null,
        "_ver": null
      }
    }






