apiVersion: v1
kind: ConfigMap
metadata:
  name: application000001-create-user-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "bookOperateService": {
        "postUserBatch": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000407&path=%2Fbook-operate%2Fuser%2Fbatch"
      },
      "session": {
        "loginId": "application000001_batch",
        "auth": {
          "member": {
            "add": true,
            "update": true,
            "delete": true
          },
          "app-wf-user": {
            "create": true
          }
        },
        "block": {
          "_value": 1000407,
          "_ver": 1
        },
        "actor": {
          "_value": 1000436,
          "_ver": 1
        }
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/application000001/create-user-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }