# Copyright 2022 NEC Corporation
# Released under the MIT license.
# https://opensource.org/licenses/mit-license.php
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-service
  name: external-db-service
  namespace: <namespace>
spec:
  type: ExternalName
  externalName: <db_endpoint>
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-service
  name: external-db-ro-service
  namespace: <namespace>
spec:
  type: ExternalName
  externalName: <db_endpoint>
