apiVersion: v1
kind: ConfigMap
metadata:
  name: root-add-region-close-target-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "catalogService": {
          "getCatalogName": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2Fname",
          "getForNs": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2F%3Fns%3D"
      },
      "bookManageService": {
          "getRegionCloseTarget": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fregion%2Fclose%2Ftarget%3Foffset%3D{offset}%26limit%3D10",
          "postOutput": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%3Foffset%3D0%26limit%3D10",
          "postOutputConditionPrepare": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%2Fcondition%2Fprepare"
      },
      "session": {
          "loginId": "root_batch",
          "auth": {
            "member": {
              "add": true,
              "update": true
            },
            "book": {
              "create": true
            }
          },
          "block": {
              "_value": 1000401,
              "_ver": 1
          },
          "actor": {
              "_value": 1000431,
              "_ver": 1
          }
      },
      "catalog": {
          "globalSettingNs": "catalog/ext/{extName}/setting/global"
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/root/add-region-close-target-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }
