apiVersion: v1
kind: ConfigMap
metadata:
  name: root-close-region-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "catalogService": {
          "getCatalogName": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2Fname",
          "getCatalog": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2F{code}",
          "getForNs": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2F%3Fns%3D",
          "getByCode": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2F{code}",
          "putCatalogExtCode": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2Fext%2F{code}"
      },
      "bookOperateService": {
          "postUserDelete": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-operate%2Fuser%2Fdelete%3FphysicalDelete%3D{physicalDelete}"
      },
      "bookManageService": {
          "getRegionClose": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fregion%2Fclose%3Foffset%3D{offset}%26limit%3D10",
          "putRegionClose": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fregion%2Fclose",
          "postOutput": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%3Foffset%3D{offset}%26limit%3D10",
          "putOutputId": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%2F{id}",
          "postMcbSearch": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fsearch",
          "postCooperateRelease": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fcooperate%2Frelease",
          "getRegionCloseTarget": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fregion%2Fclose%2Ftarget%3Foffset%3D{offset}%26limit%3D10"
      },
      "identityVerificateService": {
          "postCodeVerified": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fidentity-verificate%2Fcode%2Fverified"
      },
      "session": {
          "loginId": "root_batch",
          "auth": {
              "book": {
                  "create": true
              },
              "catalog": {
                  "update": true
              }
          },
          "block": {
              "_value": 1000401,
              "_ver": 1
          },
          "actor": {
              "_value": 1000431,
              "_ver": 1
          }
      },
      "releaseSession": {
          "operatorId": 999999999999,
          "loginId": "close-region-batch",
          "type": 3,
          "auth": {
              "member": {
                  "delete": true
              },
              "catalog": {
                  "create": true,
                  "update": true
              }
          },
          "block": {
              "_value": 1000401,
              "_ver": 1
          },
          "actor": {
              "_value": 0,
              "_ver": 0
          }
      },
      "closeRegionSession": {
          "loginId": "close-region-batch",
          "type": 3,
          "auth": {
              "book": {
                  "create": true
              },
              "catalog": {
                  "create": true,
                  "update": true
              }
          },
          "block": {
              "_value": 1000401,
              "_ver": 1
          },
          "actor": {
              "_value": 0,
              "_ver": 0
          }
      },
      "catalog": {
          "globalSettingNs": "catalog/ext/{extName}/setting/global"
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/root/close-region-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }